### ISSUE TITLE
About the trick of clbd

### ISSUE THREAD

**Issue by hkunzhe** [locuslab/breaking-poisoned-classifier#1]
Thanks for this great project! I find you have mentioned that:
> For CLBD, the original paper evaluated their method only on CIFAR-10 dataset. Here, we find that to make CLBD attack successful on ImageNet, the classifier needs to be initialized to the adversarially robust classifier that is used to generate poisoned data. We apply this small trick to train poisoned classifiers on ImageNet for CLBD.

Is this trick necessary for CIFAR-10 dataset? In my experiment, I only add the trigger in the target class (no PGD noise computed from an adversarially robust classifier). I find it also attacks successfully.

**Comment by Eric-mingjie** [comment]
yes, i think it is not necessary for CIFAR-10 dataset, the original CLBD paper shows this in their paper.

**Comment by hkunzhe** [comment]
Thanks for your reply! Adding PGD noise along with the trigger improves the attack success rate when the poison rate is small, such as 0.06 in the target class.
